### ISSUE TITLE
针对README中“与greenrobot的EventBus的不同”的话题提出几点自己的看法↓↓↓

### ISSUE THREAD

**Issue by yangyiRunning** [hehonghui/AndroidEventBus#49]
- 针对“与greenrobot的EventBus的不同”中所指出的第一个问题，EventBus 3.x之后已经通过引入注解解决了这个问题，解放了方法名，方法名可以根据开发者的业务自己定义，体现代码的自文档性。
- 针对“与greenrobot的EventBus的不同”中所指出的第二个问题，个人认为二次封装，引入tag没有必要，tag（或者叫type）之类的区别事件post源头的字段完全可以放在User或者UserEvent的实体类中，post事件时传且仅传实体类，多个post传递到一个Subscriber之后通过取出类中的tag（或者type）来通过if或switch来区别post的源头。

综上，本库之前相比于EventBus的优势随着EventBus的升级而式微，EventBus已经足够精简和友好了，没有必要再针对其进行二次封装，徒增学习成本和维护成本。

**Comment by DesignQu** [comment]
这库是不维护了么？

**Comment by yangyiRunning** [comment]
@DesignQu  我不是库的作者，但是我看最后一次提交已经是1年前的事情了，所以我揣测作者也已经不再维护这个库了。

看这个库的简介，此库是为了弥补EventBus 2.x版本的不足而生，现在EventBus 3.x的版本中那些不足已经不复存在，所以这个库也没有存在必要了。

**Comment by tpnet** [comment]
使用方法基本一致吧？  这就没什么学习成本了吧。  而且这个库才19.7kb，eventbus 52kb, 对于很多用户来说，这个库才是比较适合的其实。

**Comment by tpnet** [comment]
@yangyiRunning  使用方法基本一致吧？  这就没什么学习成本了吧。  而且这个库才19.7kb，eventbus 52kb, 对于很多用户来说，这个库才是比较适合的其实。

**Comment by tpnet** [comment]
@yangyiRunning  

使用方法基本一致吧？ 这就没什么学习成本了吧。 

这个库才19.7kb，eventbus 52kb, 。  

对于tag，你觉得放在bean里面方面还是放注解方便，肯定是放注解方便啊。

对于很多用户来说，这个库才是比较适合的，个人看法。

**Comment by DesignQu** [comment]
我觉得这个库很好，应该继续维护下去，可惜了

**Comment by KobeBryant824** [comment]
EventBus要是也加入Tag注解就真的无敌了

**Comment by JessYanCoding** [comment]
这个库优势在于小,并且支持 Tag ,方便索引订阅的方法,而 greenrobot 的 Eventbus3 ,使用的是编译时注解,效率上是有优势的,但是必须基于事件,也就是必须每个订阅事件都需要创建实体类,这样如果使用普通的数据类型作为传递参数,会非常累,而且想直接定位到订阅的方法,也没 Tag,清晰快速,而且个人不是很推荐大量使用 Eventbus ,用的太多,整个项目的架构会很乱,难以管理,如果是组件化框架,使用 Eventbus 作为中间件来通信还是不错的,因为这个 TAG ,可以根据不同的 Module 来分组,这样哪个 Moudle 的 哪个方法订阅了事件都很清楚

**Comment by JessYanCoding** [comment]
关于楼主说的在 **Event** 中 加入 **Tag**，下面是鸿神的回答，看来他和我的意见是一样的
![c2a553af7d77d01c5f9472fc7dfd9bd5](https://user-images.githubusercontent.com/15711968/42564256-e4c2d72a-8532-11e8-8e1d-35338716a53c.jpg)

**Comment by hehonghui** [comment]
这只是添加一种实现方式，至于你想怎么用，那是自己的选择。这个有点像面向对象里面你是用继承还是组合，你可以用多个Event class 进行分发，也可以通过 tag 字段进行分发。Library 只是提供基本功能，如何选择还是看自己。

**Comment by JessYanCoding** [comment]
@hehonghui 鸿神没有说您在注解上 Tag 有问题，说的是在 Event class 中加入 Tag 来达到使用同一个 Event class 分发不同的事件这种方式用问题

**Comment by hehonghui** [comment]
噢，我可能没有看清楚，忙工作的工程中看到消息所以过来交流一下。如果在 Event class 中添加tag, 再通过这个 tag 来做if-else判断那是不太合适，AndroidEventBus 最初就是要解决同一个Event class 却有不同处理逻辑的问题.

**Comment by Blankj** [comment]
# [比 EventBus 更高效的事件总线（BusUtils）](https://blankj.com/2019/07/22/busutils/)  来打个广告
